WingetBot but poggers
discordextremelist/website pull request #194
Opened 2021-01-29 20:23 UTC by Yomanz

Changes from non-poggers widgetbot to officially certified poggers widgetbot

those values in settings.json need changing to one of these so called "poggers" instances of widgetbot, don't commit them here tho!
i don't want anyone having my poggers instance information
advaith has poggers instance info he can put into production

thank,s
widgetbot taem;

2021-01-29 20:24 UTC, victiondev commented
sex

2021-01-29 20:27 UTC, Daxorinator commented
stonks! +1 for wigetbut

2021-01-29 20:29 UTC, Yomanz commented
> 
> 
> stonks! +1 for wigetbut

@advaith1 please remove this spam, thanks

2021-01-29 20:39 UTC, victiondev commented
As a member of the Poggers Society of England, Yomanz has personally received a letter of certification for this Push Request.

2021-02-10 08:32 UTC, advaith1 requested changes
instead of `settings.widgetbot.frontend` (for v2) would be better to just omit `shard` because that is now the default in the client libs (also would be more consistent; looks like shard is already not present in some areas)

also is it necessary to put the v2 backend url in settings? it's public so it doesn't seem necessary

2021-02-10 08:32 UTC, advaith1 commented on src/Routes/bots.ts
> +                body:    JSON.stringify({
in all instances of this, there should be a single space after `body:`

2021-02-10 08:32 UTC, advaith1 commented on assets/Views/templates/docs/index.ejs
> +          shard: '<%= settings.widgetbot.frontend %>'
docs should use v3 since it's the del server

2021-02-22 18:49 UTC, advaith1 approved these changes

2021-02-22 18:49 UTC, merged