Lots of fixes
discordextremelist/website pull request #256
Opened 2022-08-07 23:21 UTC by TheAlienKnight

All changes were tested *except* for autosync auto deletion for templates and servers. I'll need someone to verify that works, it should though. 

Changes:
- Edited a number of queries that were being run for counts, to only attempt to fetch the estimated mongodb count, vs actually fetching the items, putting them into an array, and checking the length. 
- Changed the interval in which "daily" metrics postings occurred, to actually be a day (23.8h to be exact) and not be posting every **5 seconds**. This was... causing a lot of problems
- Changed how the site launches, it was possible for it to become "stuck" if it happened to execute quickly- it would end up waiting for the bot to emit ready. but it never got to the point where the bot could emit ready, as it held the process up.
- If the datadog variable is an empty string, or null in the settings.json file, don't attempt to log metrics
- Changed a few files to no longer call **all** databases, even when there is a switch operator to control what metrics need to be updated. Ie: Don't waste time and resources querying things that aren't being used currently
- For automatic banlist updating, and this will only impact servers with no bans, or development testing- if there are no bans to be found, don't attempt to set a null value in redis
- For express, the cookie-session module wants an array of strings now, even though it isn't mentioned in the docs, I tried it a few times. I just tossed the settings string into an array to make it happy.

TLDR; The site shouldn't hang and die anymore, at least it didn't in my testing. I also am assuming any memory leak that did exist, has been fixed with these changes (from what I can see anyway, and the stats, this is correct).

2022-08-08 05:04 UTC, IceeMC commented
bark

2022-08-08 05:04 UTC, ConnorDoesDev commented
bork

2022-08-08 05:06 UTC, IceeMC approved these changes
pog

2022-08-08 10:56 UTC, advaith1 requested changes
for autosync deletion can you make it only delete on the specific error codes for invalid invite/invalid template? we don't want to nuke everything on outages and stuff

2022-08-08 11:00 UTC, advaith1 commented
also awaiting getters is weird; is there realistically much of a chance that the guilds/channels arent cached during operation? did you run into that?

can we just retrieve from cache and use optional chaining while accessing, so it doesn't totally break if they arent cached?

2022-08-08 11:20 UTC, TheAlienKnight commented
> also awaiting getters is weird; is there realistically much of a chance that the guilds/channels arent cached during operation? did you run into that?

I actually ran into an issue where since my test guild is small with only a few test accounts, it wasn't actually caching the members. I thought it was odd, and the only explanation I have is that perhaps discord.js doesn't attempt to cache smaller amounts of members if they aren't actively online/interacting. I changed it for that reason, I honestly agree it is weird, I wasn't expecting it to be the issue, but it ended up being one that impacted me during testing. Regardless, it doesn't hurt to have that fallback either- even if for a guild the size of DEL it doesn't happen often. There's always a better way, but I was trying to work around the existing code vs implement new methods/ways of doing things

> can we just retrieve from cache and use optional chaining while accessing, so it doesn't totally break if they arent cached?

Possibly? I can mess around with it and see it, I honestly just went with what made the most immediate sense/worked to solve the issues I ran into

> for autosync deletion can you make it only delete on the specific error codes for invalid invite/invalid template? we don't want to nuke everything on outages and stuff

I can yes, I didn't think about outages actually, good point/catch there

2022-08-08 23:58 UTC, TheAlienKnight commented
Also copying the summary here:

- No longer uselessly awaiting getters (should only happen [once if needed](https://discord.js.org/#/docs/discord.js/v13/class/Channel?scrollTo=fetch))
- Only delete templates and servers on proper [opcodes]( https://discord.com/developers/docs/topics/opcodes-and-status-codes#json)
  - Server: 10006
  - Template: 10057

2022-08-13 05:59 UTC, Carolina2k22 approved these changes

2022-08-13 06:06 UTC, Carolina2k22 requested changes
everything else seems okay

2022-08-13 06:06 UTC, Carolina2k22 commented on src/Routes/autosync.ts
> +            reasonType: 0 // since this is the only option i guess? - AJ
`reasonType` should have the value of `4`.

2022-08-13 06:06 UTC, Carolina2k22 commented on src/Routes/autosync.ts
> +            reasonType: 0 // again, assuming 0 is the only option here
`reasonType` should have the value of `5`.

2022-08-13 06:08 UTC, Carolina2k22 commented
just re whether your issues have been addressed advaith

2022-08-16 00:31 UTC, Carolina2k22 approved these changes

2022-08-23 22:54 UTC, TheAlienKnight commented
The changes I just pushed fix the audit logs trying to use require() in ESM, it also fixes the crash that occurs when bots are offline on startup. Those are the last two things @advaith1 pointed out in the discord.

2022-08-26 13:01 UTC, Carolina2k22 approved these changes

2022-08-26 16:25 UTC, merged