Some simple changes
discordextremelist/website pull request #261
Opened 2023-03-13 16:55 UTC by TheAlienKnight

Some simple changes, mostly in prep for some other fixes/additions discussed in the community discord

- Changes docker files, allowing for a less confusing setup process
- Bumps node to v18 since v17 is EOL
- Bumps Discord.js to v14, since v13 is soon to be obsolete
- Changes a few small things to allow discord.js v14 to work properly

These changes have been tested and work properly on Ubuntu 22.04.2 LTS

2023-03-14 02:31 UTC, advaith1 requested changes
DEL relies extensively on `client.api` which was replaced by `client.rest` in d.js v14, so I don't see how it's possible that this code works?

2023-03-14 02:31 UTC, advaith1 commented on .docker-compose.yml
is this file necessary? cc @IceeMC

2023-03-14 02:31 UTC, advaith1 commented on src/Util/Services/discord.ts
> +    intents: ["Guilds", "GuildMembers", "GuildPresences"],
this should use the enum

2023-03-14 16:25 UTC, TheAlienKnight commented
You are correct, it seems my docker build had not updated (I guess I forgot to prune it) and it does in fact, not operate on v14 as expected. I'll make the corrected changes tonight! Though it would sure help if discord.js documented the new discord.js/rest system, since it's entirely empty :^)

2023-03-16 00:48 UTC, TheAlienKnight commented
Added correct changes for discord.js v14! All of these *have* actually been tested correctly this time (lol) - my bad about earlier. The changes should be broken down easily with the commit messages, and side-by-side comparisons!

2023-03-16 00:54 UTC, TheAlienKnight commented on src/Util/Services/discord.ts
> +    intents: ["Guilds", "GuildMembers", "GuildPresences"],
Changed

2023-07-24 04:58 UTC, advaith1 approved these changes

2024-02-23 21:36 UTC, carolinaisslaying commented
Is this on pause or is it safe to merge this and work on the remaining patches at a later date? Also, what else needs to be done? Would like to work on some stuff myself if possible so I'm at least somewhat productive in my spare time 😅

2024-02-24 19:58 UTC, TheAlienKnight commented
Last I checked these fixes worked, though I had a server raid card go bad not too long ago and it screwed up the VM I had setup for testing this (didn't have a backup for it), so I can't 100% verify it works with the latest API changes. From what I can see though it should work fine!

2024-02-25 09:39 UTC, carolinaisslaying commented on views/templates/search.ejs
> -        if (input.value.match(/gay(\s+)?(men\s+)?.*/i)) return window.location.href = "/users/302604426781261824";
lmfao I forgot this code still existed

2024-02-25 11:54 UTC, carolinaisslaying approved these changes
Did a reasonable amount of testing, changes in the pull request itself work fine. Functions okay!

2024-02-25 11:58 UTC, merged